"""add zone, zone_zipcode, zone_city and rate tables

Revision ID: 0dd907862d09
Revises: 
Create Date: 2026-07-29 16:22:51.769966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd907862d09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_code', sa.String(), nullable=False),
    sa.Column('zone_from_id', sa.Integer(), nullable=False),
    sa.Column('zone_to_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('tolls', sa.Float(), nullable=True),
    sa.Column('parking', sa.Float(), nullable=True),
    sa.Column('tax1', sa.Float(), nullable=True),
    sa.Column('tax2', sa.Float(), nullable=True),
    sa.Column('matrix', sa.String(), nullable=True),
    sa.Column('is_default_matrix', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zone_from_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['zone_to_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_code', 'zone_from_id', 'zone_to_id', name='uq_rate_vehicle_zone_from_zone_to')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_index(op.f('ix_rates_vehicle_code'), 'rates', ['vehicle_code'], unique=False)
    op.create_table('zone_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_cities_city'), 'zone_cities', ['city'], unique=False)
    op.create_index(op.f('ix_zone_cities_id'), 'zone_cities', ['id'], unique=False)
    op.create_table('zone_zipcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_zipcodes_id'), 'zone_zipcodes', ['id'], unique=False)
    op.create_index(op.f('ix_zone_zipcodes_zipcode'), 'zone_zipcodes', ['zipcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_zipcodes_zipcode'), table_name='zone_zipcodes')
    op.drop_index(op.f('ix_zone_zipcodes_id'), table_name='zone_zipcodes')
    op.drop_table('zone_zipcodes')
    op.drop_index(op.f('ix_zone_cities_id'), table_name='zone_cities')
    op.drop_index(op.f('ix_zone_cities_city'), table_name='zone_cities')
    op.drop_table('zone_cities')
    op.drop_index(op.f('ix_rates_vehicle_code'), table_name='rates')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
